- src/main/java/picocli/CommandLine.java
- src/test/java/picocli/CommandLineTest.java
Splits the word naively at the column boundary. Don't know if this is the best way but seems to pass all the tests, including the one I made to repro this issue.
Fixes #148
> #148 Fix infinite loop when word is too large for column

- docs/autocomplete.adoc
There was forgotten class `InetAddress` in the description of enums in autocomplete documentation.
> Forgotten class InetAddress in the description of enum.

- src/main/java/picocli/CommandLine.java
Fixing the dependency on Java 7 by removing the java.util.Objects.requireNonNull calls.
The project will now be able to run on Java 5 JVMs again.
> Fix for Java 5 and 6 JVMs

- docs/index.adoc
Current kotlin sample code causes an exception at runtime:
```log
Exception in thread "main" picocli.CommandLine$InitializationException: Constant (final) primitive and String fields like private final int picocli.example.MyApp.count cannot be used as an @Option: compile-time constant inlining may hide new values written to it.
at picocli.CommandLine.init(CommandLine.java:1964)
at picocli.CommandLine$Interpreter.<init>(CommandLine.java:2040)
at picocli.CommandLine.<init>(CommandLine.java:178)
at picocli.CommandLine.<init>(CommandLine.java:167)
at picocli.CommandLine.run(CommandLine.java:971)
at picocli.CommandLine.run(CommandLine.java:925)
at picocli.example.MyApp$Companion.main(MyApp.kt:29)
at picocli.example.MyApp.main(MyApp.kt)
Process finished with exit code 1
```
Tested on …
> Avoid to overwrite compile time frozen value in Kotlin examples

- src/main/java/picocli/CommandLine.java
- src/test/java/picocli/CommandLineHelpTest.java
This PR add the ability to hide to command from the usage help text by adding a `hidden` attribute in the `Command` annotation. Resolve #277.
> Added hidden attribute on Command annotation

- src/main/java/picocli/CommandLine.java
- src/test/java/picocli/CommandLineTest.java
Extra fields have been added to ParameterException (argSpec and value) to allow more granular handling of bad parameters by the user.
> Added fields to ParameterException for #402

- src/main/java/picocli/AutoComplete.java
- src/test/java/picocli/AutoCompleteTest.java
- src/test/resources/basic.bash
- src/test/resources/hyphenated_completion.bash
- src/test/resources/picocompletion-demo_completion.bash
I've been testing the autocomplete script in `zsh`, and I came accross a few errors.
* `shopt` isn't available in `zsh`
* `compopt` doesn't seem to be understood in `zsh` even when using `bashcompinit`, `complete` with the same options works, I've added an alias when using `zsh` for `compopt`->`complete`
* added `setopt COMPLETE_ALIASES` when using zsh or the alias doesn't work properly when autocompleting
I've attempted to fix them by adding a check for the shell the script is being run under. I've tested the changes using Ubuntu Server 18.04 LTS and zsh 5.4.2, and Mac OS and zsh 5.5.1.
> Fix autocomplete script errors in zsh

- src/main/java/picocli/CommandLine.java
- src/test/java/picocli/CommandLineParseWithHandlersTest.java
- src/test/java/picocli/CommandLineTest.java
allowing `@Command` annotation on methods cuts the boilerplate in situations where a class would have to be created just to allow integration with `picocli`.
Consider a simple _tail_ example:
```java
@Command(name="tail")
public class Tail implements Runnable {
@Option(names="-n", defaultValue="10")
int n;
@Parameters()
File[] files;
public void run() {
// ... do your thing
}
}
```
versus 
```java
@Command(name="tail")
void tail(@Option(names="-n", defaultValue="10") int n, File... files) {
// ... do your thing
}
```
The attached commit is a minimal implementation and test cases for this feature.
> add support for @Command annotation on methods (in addition to classes)

- src/main/java/picocli/CommandLine.java
- src/test/java/picocli/CommandLineModelTest.java
Here's a simple fix that allows users to choose to omit regular paramLabel processing and fix it to render as-is instead (ANSI codes notwithstanding).
> #441: added support for fixing the paramLabel as-is and omit regular processing

- src/main/java/picocli/CommandLine.java
- src/test/java/picocli/CommandLineDefaultProviderTest.java
Adding support for a default value provider that could enable me to have those defaults loaded from a configuration file.
See issue #321
> 321 add support for default value provider

- src/main/java/picocli/CommandLine.java
- src/test/java/picocli/CommandLineDefaultProviderTest.java
Fixed misbehaviour that was introduced in PR #458, see #321
Now default provider overrides default or initial values only if the return
value of the provider is not null.
> Fixed default provider initial and default values overriding

- src/main/java/picocli/AutoComplete.java
- src/test/java/picocli/AutoCompleteTest.java
- src/test/resources/basic.bash
- src/test/resources/hyphenated_completion.bash
- src/test/resources/picocompletion-demo_completion.bash
> Fix short option argument handling in autocompletion scripts

- src/main/java/picocli/CommandLine.java
- src/test/java/picocli/CommandLineHelpTest.java
> Add Jansi auto detection.

- docs/index.adoc
- docs/quick-guide.adoc
Noticed there were a couple of broken links on the website because the example files directory has been renamed.
> Fix doc link for moved example files

- src/main/java/picocli/CommandLine.java
- src/test/java/picocli/CommandLineTest.java
When using setter methods for array options, the values aren't set when the setter is invoked, making it impossible to do any kind of processing on the values other than storing the array, as every value is null.
> Fill array values before setting them as value

- src/main/java/picocli/CommandLine.java
- src/test/java/picocli/CommandLineCommandMethodTest.java
- src/test/java/picocli/CommandLineMixinTest.java
This one allows Mixins to be used as method parameters, in particular for subcommands that are defined as methods.
> Allow @Mixin to be used for methods as well

- src/main/java/picocli/CommandLine.java
- src/test/java/picocli/CommandLineTest.java
Provides a nice way to get the `ArgSpec` of the option which was being overwritten before throwing an `OverwrittenOptionException`. The `ArgSpec` is retrieved through `OverwrittenOptionException#getOverwritten()`, which can be taken advantage of in a custom `IExceptionHandler2` to automate exception handling, generate custom error messages, etc.
I was in the process of writing a custom `IExceptionHandler2` and noticed some `ParameterException`s have convenience methods for accessing the root of the exception (see `MissingParameterException#getMissing()`) and thought `OverwrittenOptionException` was missing such a method. It's a tiny pr, but seems useful to me at least. Thanks for the consideration.
> Add a way to get the argument attempted to be overwritten from an OverwrittenOptionException

- docs/index.adoc
Small fix to include mention of command methods for options using collections.
> DOC: small fix to include mention of command methods for options using collections

- src/main/java/picocli/CommandLine.java
- src/test/java/picocli/CommandLineHelpTest.java
Print help run into infinite loop when length of the text equals to `columnValue.maxLength` and offset is non zero.
> Print help infinite loop fix

- docs/index.adoc
When viewing https://picocli.info/, the link resolves to the non-existing https://picocli.info/src/main/java/picocli/CommandLine.java
> fix(doc): link to CommandLine.java

- src/test/java/picocli/CommandLineTest.java
- src/test/resources/argfile-simplified-quoted.txt
- src/test/resources/argfile-simplified.txt
The test for #551 is failing on `List`-based arguments. Before I move on with writing extra coverage, we should probably agree on how to deal with this. WDYT @remkop?
> Add first failing test for #551

- src/main/java/picocli/CommandLine.java
- src/test/java/picocli/CommandLineTest.java
The property is `picocli.trimQuotes`.
When set to `true` or when left empty, quote trimming will be enabled by default. Otherwise, the default is `false`. Regardless of the value of the property, the value can still be overriden through the usual API - therefore there is no break in backwards compatibility.
> Allow for enabling quote trimming via a system property

- src/main/java/picocli/CommandLine.java
- src/test/java/picocli/CommandLineHelpTest.java
Issue #530 
Changes based on stechios changes and your suggestions.
Does this comply with your suggestions? Just say what you think.
First ever pull request, so I don't know what I am doing github-wise.
I assume that every new Help(...) inside of Help needs to be replaced by the factory?
For me all of this usage customization only has a value when Help.detailedSynopsis is split into multiple methods. This affects synopsis Help.synopsis(int). So I suggest making the switch between custom, abbreviated and detailed synopsis in Help.sections. Plus some code reuse to implement Help.synopsis(int) if the interface should not break. I think it fits this issue, or should i open a new issue for that?
My agenda: I like to see some parameters in usage instead of commandSpec.qualifiedName() and want …
> [#530] Usage message customization (2)

- picocli-shell-jline3/src/test/java/picocli/shell/jline3/example/Example.java
Use defaultParser to split readLine output in order to manage correctly escaped chars and quoted arguments
> JLine3 example: use defaultParser to split readLine output

- src/main/java/picocli/AutoComplete.java
In some cases using the DefaultFactory when instantiating CommandLine could cause subcommands that require a specific implementation to fail to be created. This commit makes the CommandLine instance use the IFactory implementation passed by the user to the AutoComplete command (if any) which should resolve this issue.
Closes #601
> Make CommandLine in AutoComplete use correct IFactory implementation

- src/main/java/picocli/CommandLine.java
- src/test/java/picocli/CommandLineHelpTest.java
Percent signs shall be escaped in the description text as it is going
to be passed to String.format. If the default value contains (single) %
signs then using the built-in DEFAULT-VALUE variable would lead to a
warning message. This is avoided by escaping any % signs in the
DEFAULT-VALUE variable when used in the description.
This is related to #615 and its fix. I have an option with a default value of "%s - page %d of %d" and using ${DEFAULT-VALUE} in the description leads to the warning message. A workaround would have been to not use ${DEFAULT-VALUE} but instead writing the default value with doulbe % signs in the description but I definitely prefer the use of the variable just in case the default changes some time later.
> Change % to %% when using ${DEFAULT-VALUE} in option description

- bnd.bnd
- build.gradle
* added the bnd plugin to the build
* defined a bnd.bnd file to handle the package export
> [#734] Make the picocli jar OSGi friendly

- src/main/java/picocli/CommandLine.java
- src/test/java/picocli/TextTableTest.java
Automatically split lines in TextTable
> Automatically split lines in TextTable #696

- docs/index.adoc
- picocli-shell-jline2/README.md
- picocli-shell-jline2/src/test/java/picocli/shell/jline2/example/CustomFactory.java
- picocli-shell-jline2/src/test/java/picocli/shell/jline2/example/Example.java
- picocli-shell-jline2/src/test/java/picocli/shell/jline2/example/InteractiveParameterConsumer.java
I also tested interactive options in the jline3 variant. They work fine. 
Changes for #767
> Extended example of picocli-shell-jline2 with IParameterConsumer

- picocli-codegen/README.adoc
The provided flag should be added as the scope:
`<scope>provided</scope>`
> Fixing the provided flag usage in the read me

- picocli-codegen/src/main/java/picocli/codegen/aot/graalvm/ReflectionConfigGenerator.java
Fix #803 by visiting the IParameterConsumers
> Visit Parameter Consumers when doing GraalVM reflection generation

- picocli-annotation-processing-tests/src/test/java/picocli/codegen/aot/graalvm/processor/NativeImageConfigGeneratorProcessorTest.java
- picocli-annotation-processing-tests/src/test/resources/picocli/issue803/Issue803.java
- picocli-annotation-processing-tests/src/test/resources/picocli/issue803/issue803-reflect-config.json
As requested, some tests for #803. Can't get them to work locally for some reason though, as I commented in #803
> Add tests for #803

- src/main/java/picocli/CommandLine.java
- src/test/java/picocli/ModelOptionSpecTest.java
- src/test/java/picocli/ModelPositionalParamSpecTest.java
There seems to be no public way to get from an `ArgSpec` to the command model it belongs to. Expose the existing field with a getter method.
My use case for this is so I can write a single generic `IDefaultValueProvider` that is sensitive to which subcommand it is getting a default for. This makes it simpler to implement [Bazel-style config files](https://docs.bazel.build/guide.html#bazelrc-syntax-and-semantics) that provide a uniform way to override defaults for all command-line options.
(If I'm overlooking something obvious, please advise).
> Add command() to ArgSpec

- src/main/java/picocli/CommandLine.java
Picocli sometimes uses `toString()` to get the name of an enum constant, at other times `name()`. These can be different if one overrides `toString()` in the `enum` type declaration, and in that case it is probably because one _wants_ the external name of the enum constant to be different from its source-code name. So that is what options should work in terms of.
The `${COMPLETION-CANDITATES}` usage-help interpolation for enum-type arguments already uses `toString()` to display the options.
This PR fixes the default type converter such that it works in terms of `toString()` rather than `name()`. It initially will try to match the argument against the raw name using `Enum.valueOf()` because that might use more efficient lookup tables internally (and arguably if someone creates an enum …
> Use toString() to match enum constants

- src/main/java/picocli/CommandLine.java
Hi,
while reading the API docs of the newly introduced PropertiesDefaultProvider, I realized that parts of the javadoc were missing. The attached patch fixes this issue.
A second patch fixes all javadoc errors that were present in the project.
Thanks for considering my input.
> Javadoc issues

- picocli-examples/src/main/groovy/picocli/examples/UserManualExample.groovy
- picocli-examples/src/main/groovy/picocli/examples/UserManualScriptExample.groovy
- picocli-examples/src/main/groovy/picocli/examples/checksum-with-banner.groovy
- picocli-examples/src/main/groovy/picocli/examples/checksum-without-base.groovy
- picocli-examples/src/main/groovy/picocli/examples/checksum.groovy
- picocli-examples/src/main/groovy/picocli/examples/simple.groovy
- picocli-groovy/README.md
I realised that the README.md of the `picocli-groovy` lists an example that states in the description of the option `algorithm`: 
`See [1] for more details.`
There is no footer with a reference [1], though.
Removed this passage.
> Minor improvements and corrections to groovy examples

- src/main/java/picocli/CommandLine.java
Also added @Command annotation for sake of clarity.
> Fix syntax error in javadoc

- picocli-codegen/README.adoc
- src/main/java/picocli/CommandLine.java
Happy new year!
Get well soon!
This patch corrects a few broken links in the javadocs.
There are two more broken links, I couldn't figure out how to resolve them:
```
picocli\src\main\java\picocli\CommandLine.java:394: warning - Tag @see: can't find Help(CommandSpec, Help.ColorScheme) in picocli.CommandLine.Help
picocli\src\main\java\picocli\CommandLine.java:12755: warning - Tag @link: can't find Help(picocli.CommandLine.Model.CommandSpec, picocli.CommandLine.Help.ColorScheme) in picocli.CommandLine.Help
```
Maybe you can help out?
> Fix broken links in javaDoc

- docs/index.adoc
- picocli-examples/src/main/java/picocli/examples/subcommands/SubCmdsViaMethods.java
- picocli-examples/src/main/kotlin/picocli/examples/kotlin/Checksum.kt
- picocli-examples/src/main/kotlin/picocli/examples/kotlin/MyApp.kt
- picocli-examples/src/main/kotlin/picocli/examples/kotlin/interactive/PasswordDemo.kt
- picocli-examples/src/main/kotlin/picocli/examples/kotlin/subcommands/SubCmdsViaMethods.kt
This patch provides further example files, coded both in Java and Kotlin. References to the newly added files were added to the manual, too.
This patch also corrects the Kotlin MyApp example which currently does not compile:
```
companion object {
@JvmStatic fun main(args: Array<String>) {
CommandLine.run(MyApp(), *args)
}
}
```
Inside the companion object, `CommandLine.run()` is called, however, MyApp implements `Callable` and not `Runnable`.
Since both methods `run()` and `call()` are deprecated, I changed this to `CommandLine(MyApp()).execute(*args)`.
In order to prevent these kind of errors in the future, I would propose to add a task `compileKotlin` to the file `build.gradle` of the `picocli-examples` module.
> More Java and Kotlin examples

- docs/index.adoc
websites dependencies in spring boot section are outdated (4.0.1 currently)
> latest snapshot version for spring dependencies

- docs/index.adoc
${groupId} and ${artifactId} are deprecated and cause the following warning during the build:
```
[WARNING] The expression ${groupId} is deprecated. Please use ${project.groupId} instead.
[WARNING] The expression ${artifactId} is deprecated. Please use ${project.artifactId} instead.
```
> Use ${project.groupId} instead of deprecated ${groupId}

- src/main/java/picocli/CommandLine.java
- src/test/java/picocli/HelpTest.java
* changed terminal width detection regex pattern for Windows
* check for process termination in order to fail faster
> #991 more robust terminal width detection for international Windows versions

- src/main/java/picocli/CommandLine.java
- src/test/java/picocli/ColorSchemeTest.java
- src/test/java/picocli/ExecuteLegacyTest.java
- src/test/java/picocli/ExecuteTest.java
Changes:
1. Add `errors` and `stackTraces` to Help.ColorScheme
2. Change the `internalHandleParseException` method to use `colorScheme.errorText(ex.getMessage())`, instead of just `ex.getMessage()`
3. Add a method called `exceptionToColorString` to convert exceptions to ANSI colored strings.
4. Change the `handleUnhandled` method to use `exceptionToColorString`
Tests: existing tests updated, no new test introduced
Documentation: JavaDoc updated, no change to other documentations
> Attempting to fix issue #845

- src/main/java/picocli/CommandLine.java
- src/test/java/picocli/CommandLineTest.java
- src/test/java/picocli/LinkedCaseAwareMapTest.java
This is an alternative PR to #1020 , follows a somewhat different approach, trying to solve #9 .
Currently it is only a draft, feedbacks are welcomed. Tests are partially added, not fully tested.
No previous tests are broken due to the new changes.
> Another implementation of case-insensitive support for subcommands and options (#9)

- src/main/java/picocli/CommandLine.java
- src/test/java/picocli/ArgGroupTest.java
This is a very simple draft to fix #1027, and does not break any previous tests.
Could anyone check whether any behaviour breaks with this?
> Add experimental support for repeatable ArgGroup positional parameters (#1027)

- src/main/java/picocli/CommandLine.java
Removed duplicated null checking, fix several potential NullPointerException.
Also fixed NPE when user Ctrl+D in password prompt.
> Code cleanup and minor fixes

- src/main/java/picocli/CommandLine.java
- src/test/java/picocli/ColorSchemeTest.java
- src/test/java/picocli/ExecuteTest.java
Injecting ANSI characters into ColorSchemeStringWriter, instead of reimplementing `printStackTrace()`.
> Fix issue #1048

- src/main/java/picocli/AutoComplete.java
- src/main/java/picocli/CommandLine.java
This PR removes redundant modifiers and initializations, unused variables, incorrect javadoc references, etc.
The `static` modifiers in inner interfaces are removed since they are static by default, and removing them should not break binary compatibility (the md5sums are the same). Let me know if those are preferred to be kept.
> Code cleanup

- src/main/java/picocli/CommandLine.java
- src/test/java/picocli/AtFileTest.java
Written to solve #1074 , this exposes the expanded argument list that picocli keeps internally. I had to reverse the list since it was stored as a stack, which I believe means we're copying the full argument list twice into memory. Ideally we'd use some sort of reversed view and not duplicate it, but since we don't have guava or anything like that it's slightly ugly imo. Happy to update with that though.
> Expose the expanded argument list from ParseResult

- picocli-codegen/src/main/java/picocli/codegen/docgen/manpage/ManPageGenerator.java
- picocli-codegen/src/test/java/picocli/codegen/docgen/manpage/ManPageGeneratorTest.java
- picocli-codegen/src/test/resources/testHidden.manpage.adoc
> Excludes hidden options, params, and subcommands from man page generation

- src/main/java/picocli/CommandLine.java
the factory should be passed when creating a CommandSpec copy and not degrade to the DefaultFactory
> fix factory used for repeatable subcommands

- picocli-codegen/src/main/java/picocli/codegen/docgen/manpage/ManPageGenerator.java
I found a fairly easy way to overcome the encoding issues addressed in #1109. I guess the proposed changes should be sufficient here. Generating man pages for the [I18NDemo](https://github.com/remkop/picocli/blob/master/picocli-examples/src/main/java/picocli/examples/i18n/I18NDemo.java) given in the examples section of the repo works perfect now.
Unfortunately, the patch breaks two exiting tests and I didn't find an easy way to make them work again. Can you have a look here?
Also while not strictly necessary, I would suggest to explicitly add the encoding attribute to the generated .adoc files (second commit).
Do we need test(s) for the patch? If so, can you take over or can you bring me on the right track here? Thanks.
> PR: manpage generator: overcome encoding issues (#1109)

- docs/index.adoc
- docs/index.html
I found a typo in the "Guice Example".
- The method variable name of `GuiceFactory#create` is `aClass`.
- I think the 1st argument of `new CommandLine` should have annotations of picocli, so we should specify a implemented class (i.e. `InjectionDemo.class`) not `Runnable.class`
- If we specify the implemented class, bind definition for `Runnable.class` might not be unnecessary.
> DOC: Fix typo in picocli user manual

- src/main/java/picocli/CommandLine.java
- src/test/java/picocli/CaseAwareLinkedMapTest.java
- src/test/java/picocli/CommandLineTest.java
- src/test/java/picocli/HelpSubCommandTest.java
This pull request will fix #1156.
> Fix #1156, make HelpCommand respect subcommands case-sensitivity and abbreviation

- src/test/java/picocli/TypeConversionTest.java
Some DNS setups such as ISP "DNS hijacking" will return an IP address for garbage names. Using the ".invalid" domain specified in RFC 6761 makes the test more reliable.
> Use .invalid domain name for InetAddress test

- docs/index.adoc
- docs/quick-guide.adoc
In an order to eventually close #890, I authored this PR, I hope you like it.
Feel free to perform some polishment like you did before.
> Extend and improve documentation on subcommands (#890)

- build.gradle
- docs/quick-guide.adoc
This PR, ready for merging, supersedes #1188.
This is my attempt to add online execution to the quick guide.
Please let me know how you like it.
> Quick guide: online execution of sample apps

- docs/A-Whirlwind-Tour-of-Picocli-docinfo.html
- docs/A-Whirlwind-Tour-of-Picocli.adoc
- docs/autocomplete-docinfo.html
- docs/autocomplete.adoc
- docs/docinfo.html
- docs/index-docinfo.html
- docs/index.adoc
- docs/quick-guide-docinfo.html
- docs/quick-guide.adoc
Using the button, you can copy textual content of code block to clipboard.
> Documentation: add copy button to code blocks

- docs/index.adoc
See discussion [here](https://github.com/remkop/picocli/pull/1196#issuecomment-702616049).
> User manual: online execution of checksum sample app

- build.gradle
- docs/index.adoc
This PR adds a second tab to the checksum souce code, showing the Kotlin version of the app.
I hope you like the idea (as I do).
This is work in progress, and I'm willing to push this a bit further. Prior to that, I would like your info/opinion on the following topics:
- I realized that current `coderay` source highlighter does not support kotlin yet. Source highlighter `highlight-js` supports much more languages. I see that `highlight-js` is mentioned in the header of `index.adoc`, it is commented out, however. Did you experiment with `highlight-js` already? What were you experiences? Why did you abandon it?
- With source codes available in multiple languages, we have to keep the description of the code (especially in the source code) as generic as possible. I had a quick look on the …
> Checksum example: add Kotlin source code on second tab

- build.gradle
- gradle.properties
- picocli-codegen/build.gradle
- picocli-examples/build.gradle
This PR updates gradle Asciidoctor plugin to latest version.
After applying this PR, `gradle ascii` works again on master.
Unfortunately, now tabbed panes do not show up any more. :-(
Seems like the used extension is not picked up any more by the new version. I will look into that soon.
For now, the produced `index.html` is **not** ready for being published to the web site.
> Update to latest Asciidoctor gradle plugin

- docs/index.adoc
This PR changes changes source highlighter to `rouge` since the current highlighter `coderay` does not support Kotlin and Scala.
This gives a better result for the listings in chapter 30 `Picocli in Other Languages`.
> Add source code highlighting for Kotlin, Scala and Groovy

- docs/index.adoc
This PR adds checksum sample app coded in Groovy and Scala.
For Groovy language, I decided to add a Groovy scipt.
Should we add Groovy example with class, too? What do you think?
> Manual: add checksum sample app coded in Groovy and Scala

- build.gradle
After updating to latest asciidoctor gradle plugin (#1202), copy buttons in code blocks were [not displayed any more](https://github.com/remkop/picocli/pull/1202#issuecomment-703971199).
This is corrected with this PR.
> Fix: Show copy buttons in code blocks (#1198)

- picocli-shell-jline2/README.md
- picocli-shell-jline3/README.md
Minor documentation improvement. 
*Story behind it*
I wanted to try out the JLine integration. I copy pasted the example and then simply started to add imports. However, my IDE couldn't find the imports, so I was obviously missing some dependency. But the dependency to be used for this integration is not mentioned anywhere in the docs.
> Add Maven coordinates to JLine2/3 modules

- docs/index.adoc
Time permitting, I will add more tabs with source code. So don't worry if you don't find time to recreate the html page immediately.
> Manual, section subcommands: add several tabs with Kotlin source code

- docs/index.adoc
This PR improves user manual by
- adding missing semicola to Java code sample
- adding further tabs with Kotlin source to user manual
- adding instructions on usage help for nested subcommands
> User manual: documentation improvements

- docs/index.adoc
This PR adds adds the Kotlin version for the Micronaut example (chapter 22).
When working on this, I extended the description a bit.
Also, the example was sligthly altered, it now closely resembles the auto-generated sample source file.
Also I removed these lines
```
@Client("https://api.github.com")
@Inject
var client: RxHttpClient? = null
```
since they weren't used inside the sample. As a side effect, number of imports could be reduced after removal of these lines.
Feel free to polish my description!
> Micronaut example: add Kotlin version, extended description of Micronaut use

- src/main/java/picocli/CommandLine.java
Calling getClass() is likely to return an internal Proxy class (ie
com.sun.proxy.$Proxy1) so use annotationType() instead.
Assignment in an if statement is ambiguous so wrap in parens to make it
obvious that it's intended.
This are things that our compiler will fail on.
> Update patterns that our compiler will complain about.

- gradle.properties
picocli-spring-boot-starter module has a dependency on spring-boot-starter 2.2.2.RELEASE, which is outdated.
Starting a project with this outdated module using Java 15 results in: `Unsupported class file major version 59`.
This PR fixes this by bumping spring-boot starter to latest version 2.3.5.RELEASE.
> Bump Spring-Boot-Starter to latest version

- docs/index.adoc
This PR brings an extended Spring Boot example
- details on how to set up a skeleton Spring Boot project
- a fully working, meaningful sample app.
This comes with a price, the section is much longer now. I didn't know where to shorten without putting the Sping Boot style of the example at risk.
> Manual: extended Spring Boot example

- build.gradle
- picocli-annotation-processing-tests/build.gradle
- picocli-codegen/build.gradle
- picocli-examples/build.gradle
- picocli-groovy/build.gradle
- picocli-shell-jline2/build.gradle
- picocli-shell-jline3/build.gradle
- picocli-spring-boot-starter/build.gradle
`gradlew --warning-mode all` now does not emit any warnings any more.
> Fix gradle warnings

- README.md
- build.gradle
- docs/index.adoc
- docs/quick-guide.adoc
- gradle/wrapper/gradle-wrapper.properties
- picocli-codegen/README.adoc
- picocli-codegen/build.gradle
- picocli-examples/annotation-processing/example-gradle-project-kotlin-graal-nativeimage/build.gradle
- picocli-examples/annotation-processing/example-gradle-project/build.gradle
- picocli-examples/generate-man-pages/example-gradle-project/build.gradle
- picocli-examples/generate-man-pages/example-maven-project/pom.xml
- picocli-spring-boot-starter/README.md
This PR adds Kotlin + Scala versions to the subcommands example of the quick guide.
It adds Groovy versions to sample code in chapter 17 'Subcommands' of the quick guide.
It contains some minor fixes to the gradle build scripts of the example projects:
- avoid deprecation warnings
- bump to latest version of the dependencies, like ascii-doctor-plugin, ... 
It also fixes deprecated syntax in gradle build scripts in a few README files.
> Quick guide: add Kotlin + Scala versions

- src/main/java/picocli/CommandLine.java
- src/test/java/picocli/SubcommandTests.java
This was an attempt to fix #1250 following the proposal there, but this causes other test failures. I am leaving this on a branch/PR for further examination if you think it is salvageable.
> Shared initialized set

- picocli-shell-jline3/src/main/java/picocli/shell/jline3/PicocliCommands.java
- picocli-shell-jline3/src/test/java/picocli/shell/jline3/example/Example.java
Allow users of picocli-shell-jline3 to use `clear` command and a nicer `help` command.
- The clear screen command is provided out of the box by jline2, and similarly should be built into `picocli.shell.jline3.PicocliCommands`. This change allows users of `PicocliCommands` to include a clear screen command with a single line: `picocliCommands.includeClearScreenCommand(reader);` - see the example.
- The help command is provided by jline3 by default, but picocli help is much nicer. This change allows users of `PicocliCommands` to override the jline3 help command with a single line: `systemRegistry.register("help", picocliCommands);` - see the example.
> Allow users of picocli-shell-jline3 to use `clear` command and a nicer `help` command

- src/main/java/picocli/CommandLine.java
- src/test/java/picocli/CommandModelTransformersTest.java
- src/test/java/picocli/CommandSubcommandFilterTest.java
> Support user-defined model transformations after initialization and before parsing

- picocli-examples/src/main/java/picocli/examples/interactive/UserPasswordDemo.java
- src/main/java/picocli/CommandLine.java
- src/test/java/picocli/InteractiveArgTest.java
PR for #802.
- If `echo` is true, just uses `BufferedReader#readLine` not `Console#readPassword` to read user input.
- If `prompt` is not empty, the specified string will be displayed to the end user for an interactive option.
- The default values:
- `echo` : false
- `prompt` : empty string
Here is the result of a sample class added by this PR. I use Windows 10.
```bash
PS C:\xxxxx\picocli> java -version
openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9.1+1)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.9.1+1, mixed mode)
PS C:\xxxxx\picocli> java -cp "build/libs/picocli-4.5.3-SNAPSHOT.jar;picocli-examples/build/libs/picocli-examples.jar" picocli.examples.interactive.UserPasswordDemo "sample action"
Enter your user: dummy
Enter your password: …
```
> Support echo and prompt for an interactive option

- docs/index.adoc
- docs/index.html
I find no @ParentObject annotation. Does it need to be replaced by @ParentCommand, as it seems to me it is the right annotation ?
> documentation fix: @ParentObject -> @ParentCommand

- picocli-shell-jline2/README.md
- picocli-shell-jline2/src/test/java/picocli/shell/jline2/example/Example.java
- picocli-shell-jline3/README.md
- picocli-shell-jline3/src/test/java/picocli/shell/jline3/example/Example.java
Though certainly not wrong, `Ctl-D` seems to be rarely used, so I propose to change it to `Ctrl-D` ( that's what I see on English keyboards and in many other places).
> JLine: change keystroke syntax 'Ctl-D' to more common used syntax 'Ctrl-D'

- docs/index.adoc
- picocli-examples/build.gradle
This PR adds Kotlin versions for the new code samples in picocli 4.6 (`IModelTransformer`, `IParameterProcessor`).
While working on the `IParameterProcessor` sample, I made minor changes to the code sample and to the documentation in order to improve readability and intelligibility. I hope you like them.
Additionally, I added a third column to the comparison table `PicocliBaseScript2` vs. `PicocliBaseScript`.
> Docu, new code samples: Kotlin versions, minor changes

- docs/index.adoc
- Adding CAUTION admonitions about the use of static classes to ITypeConverter and IModelTransformer (#1297)
- Manual, chapter '4.2.2 Multi Parameter Type Converters': adding Kotlin version for code sample
> CAUTION admonitions, Kotlin code sample

- picocli-codegen/README.adoc
Fix the following warnings in Maven when using configuration specified in codegen documentation:
```
The expression ${groupId} is deprecated. Please use ${project.groupId} instead.
The expression ${artifactId} is deprecated. Please use ${project.artifactId} instead.
It is highly recommended to fix these problems because they threaten the stability of your build.
For this reason, future Maven versions might no longer support building such malformed projects.
```
> Fix use of deprecated Maven properties

- src/main/java/picocli/CommandLine.java
- src/test/java/picocli/ExecuteTest.java
- src/test/java/picocli/HelpSubCommandTest.java
- src/test/java/picocli/Issue1320.java
> Fix bad encoding when creating default PrintWriter

- build.gradle
- picocli-annotation-processing-tests/build.gradle
- picocli-codegen/build.gradle
- picocli-groovy/build.gradle
- picocli-shell-jline2/build.gradle
- picocli-shell-jline3/build.gradle
- picocli-spring-boot-starter/build.gradle
Fix wrong `Implementation-Version` and `Specification-Version` introduced by bdf774e3c1984da1ed7660ea3cacb2760e29edf0 such as (notice the `task ':jar' property 'archiveVersion'`):
```
Implementation-Version: task ':jar' property 'archiveVersion'
Import-Package: groovy.lang
Main-Class: picocli.AutoComplete
Multi-Release: true
Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.5))"
Specification-Title: picocli
Specification-Vendor: Remko Popma
Specification-Version: task ':jar' property 'archiveVersion'
```
(from https://repo1.maven.org/maven2/info/picocli/picocli/4.6.1/picocli-4.6.1.jar / `META-INF/MANIFEST.MF`)
> chore: fix incorrect version in MANIFEST.MF

- .github/workflows/gradle-wrapper-validation.yml
- gradle/wrapper/gradle-wrapper.properties
Official Gradle Wrapper Validation Action enabled to ensure binary wrapper is not tampered with.
See: https://github.com/marketplace/actions/gradle-wrapper-validation
> Upgrade Gradle to 6.8.2 and enable Official Gradle Wrapper Validation GitHub Action

- build.gradle
- picocli-codegen/build.gradle
- picocli-groovy/build.gradle
- picocli-shell-jline2/build.gradle
- picocli-shell-jline3/build.gradle
- picocli-spring-boot-starter/build.gradle
Dedicated DSL usage should be safer in order to detect typos.
This has the side effect of changing the order of the XML elements, but
this is more canonical this way.
```diff
$ diff -u3 picocli-groovy/pom-default.xml picocli-groovy/build/publications/MyPublication/pom-default.xml
--- picocli-groovy/pom-default.xml 2021-02-21 11:18:23.755921800 +0800
+++ picocli-groovy/build/publications/MyPublication/pom-default.xml     2021-02-21 11:20:45.363477600 +0800
@@ -1,18 +1,10 @@
<?xml version="1.0" encoding="UTF-8"?>
-<project xmlns="http://maven.apache.org/POM/4.0.0" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
+<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 …
```
> chore: use type-safe DSL instead of direct XML manipulation for pom.xml

- picocli-codegen/src/main/java/picocli/codegen/docgen/manpage/ManPageGenerator.java
- picocli-codegen/src/test/resources/import.manpage.txt.adoc
- picocli-codegen/src/test/resources/manpagegenerator/main_class-gen-manpage.adoc
- picocli-codegen/src/test/resources/manpagegenerator/main_class.adoc
- picocli-codegen/src/test/resources/manpagegenerator/top-level-command-subcommand-gen-manpage.adoc
- picocli-codegen/src/test/resources/manpagegenerator/top-level-command-subcommand.adoc
- picocli-codegen/src/test/resources/manpagegenerator/top-level-command-visible.adoc
- picocli-codegen/src/test/resources/manpagegenerator/top-level-command.adoc
- picocli-codegen/src/test/resources/myapp.manpage.adoc
- picocli-codegen/src/test/resources/testEndOfOptions.manpage.adoc
- picocli-codegen/src/test/resources/testEndOfOptionsWithoutOptions.manpage.adoc
- picocli-codegen/src/test/resources/testHidden.manpage.adoc
- picocli-codegen/src/test/resources/testHiddenOptions.manpage.adoc
> add tags for empty sections in adoc man page

- docs/index.adoc
- picocli-examples/src/main/java/picocli/examples/i18n/localecontrol/LocaleControl.java
- picocli-examples/src/main/java/picocli/examples/i18n/localecontrol/bundle.properties
- picocli-examples/src/main/java/picocli/examples/i18n/localecontrol/bundle_de.properties
- picocli-examples/src/main/kotlin/picocli/examples/kotlin/i18n/localecontrol/LocaleControl.kt
- picocli-examples/src/main/kotlin/picocli/examples/kotlin/i18n/localecontrol/bundle.properties
- picocli-examples/src/main/kotlin/picocli/examples/kotlin/i18n/localecontrol/bundle_de.properties
This PR adds a new chapter `19.6 Controlling the locale` to the manual, as proposed in  #1326.
Also sample files are added to the `picocli-examples` module.
> Controlling the locale: documentation + examples

- picocli-codegen/src/main/java/picocli/codegen/docgen/manpage/ManPageGenerator.java
- picocli-codegen/src/test/resources/manpagegenerator/main_class.adoc
- picocli-codegen/src/test/resources/manpagegenerator/top-level-command-subcommand.adoc
- picocli-codegen/src/test/resources/manpagegenerator/top-level-command.adoc
- picocli-codegen/src/test/resources/testHidden.manpage.adoc
subcommands get separate html files, nice if html generated from asciidoc could link them.
Added an xref for each subcommand and updated tests. I believe an xref like this doesn't hurt anything, and helps with linking is possible (html and pdf). That said, I know just enough asciidoc to be dangerous, so...
> add xref for subcommands

- docs/index.adoc
Can you do me a favor and regenerate the html docs, please? Thanks.
> Manual: Extending chapter 28.3 'Testing the Exit Code'

- docs/index.adoc
This PR adds Kotlin test samples for testing envorinment variables to the manual. It also fixes a compilation issue and two other minor quirks for the existing Java samples.
> Documentation, chapter 'Testing environment variables:': add Kotlin test sample

- picocli-shell-jline2/README.md
See #1397 for more details.
**Note that 2nd commit should maybe not integrated** but on my side Ctrl-D do nothing and only Ctrl-C is able to stop the application. If this is an issue on my side please just integrate the first commit. 
**Completely out of topic** but I cloned the repo and do nothing special and I already have some repo modification ? (maybe a gitIgnore issue ?)
See :
> Update Jline2 README.md to add some recommended workaround about not ANSI compatible terminal

- docs/index.adoc
- src/main/java/picocli/CommandLine.java
The default arity for boolean options is 0..1 and no longer 0.
Closes https://github.com/remkop/picocli/issues/1398.
> Documentation: Update boolean arity

- src/main/java/picocli/CommandLine.java
- src/test/java/picocli/ModelCommandSpecTest.java
Updated CommandSpec.remove(ArgSpec arg) method to remove the arg from args (List<ArgSpec>) and test case corresponding to same.
Ref: #1434
> Updated CommandSpec.remove(ArgSpec arg) #1434

- src/main/java/picocli/AutoComplete.java
- src/main/java/picocli/CommandLine.java
- src/test/java/picocli/AutoCompleteTest.java
This seems to fix #1388 regression, and I have added a new test for the issue.
However, this cause #1352 `testIssue1352_SubcommandNameResourceBundle` to fail, which seemed to be caused by `descriptor.commandName` is `${project.cli.command}`, and it's from `commandLine.getSubcommands().entrySet().?.getKey()`, indicating there might be some issue in resource bundle propagation for subcommands.
@remkop any thoughts?
> [#1388] Fix subcommand aliases autocomplete regression

- picocli-codegen/src/main/java/picocli/codegen/annotation/processing/AbstractCommandSpecProcessor.java
An annotation target-type error message has a typo that says "Cannot only process" when it should say "Can only process".
> Typo in annotation target-type error message

- src/main/java/picocli/AutoComplete.java
- src/test/java/picocli/AutoCompleteTest.java
- src/test/resources/picocompletion-demo-help_completion.bash
- src/test/resources/picocompletion-demo_completion.bash
By setting the bash separator to `\n`, `COMPREPLY` now contains file names with spaces without splitting them, and can autocomplete correctly.
After some preliminary testing, only files with line feed `\n` in their name cannot be autocompleted correctly, but `ls` seem to behave the same, so looks good to me.
This pull request will close #1458.
> Fix incorrect autocomplete if file name contains space

- src/main/java/picocli/AutoComplete.java
- src/test/java/picocli/AutoCompleteTest.java
First of all, thanks for the amazing project and all the effort in it @remkop !
This is a follow up from an issue experienced in the Keycloak project:
https://github.com/keycloak/keycloak/pull/8875
Sorry for directly opening a PR instead of an Issue, but I do believe that this change is more self-explanatory in code 🙂 
Rationale:
- `./` breaks the autocomplete script on ZSH
- `.bash` and `.sh` autocompletion extensions are always automatically generated
Sanitizing the internally used `scriptName` sounds like a first step in the right direction, wdyt?
> Remove execution and extension characters in the generated autocomplete script

- picocli-codegen/src/main/java/picocli/codegen/annotation/processing/AbstractCommandSpecProcessor.java
Improved AbstractCommandSpecProcessor#isSubcommand(ExecutableElement, RoundEnvironment):
Simplified
Improved performance
Fixed possible correctness bug if RoundEnvironment#getElementsAnnotatedWith(Class) ever returns an unmodifiable Set
> Improved AbstractCommandSpecProcessor#isSubcommand(ExecutableElement, RoundEnvironment)

- picocli-examples/src/main/kotlin/picocli/examples/kotlin/optional/SingleOptions.kt
- src/main/java/picocli/CommandLine.java
Fix build warnings.  See commit messages.
> Fix build warnings

- src/main/java/picocli/CommandLine.java
Improved `DefaultFactory#create(Class<T>)`:
- Only handle `cls` argument being a `Map` or subtype differently than normal if `cls` is an interface
- Create `TreeMap` if `cls` argument is `SortedMap` or sub-interface
- Simplified normal instantiation:
- no longer call deprecated method
- only try `setAccessible(true)` if it might make a difference
> Improved DefaultFactory#create(Class<T>)

- src/main/java/picocli/CommandLine.java
Simplified CommandSpec#validateSubcommandName(…) by returning ASAP when the correct return value is first known.
It makes it much more understandable.
> Simplified CommandSpec#validateSubcommandName(…)

- docs/A-Whirlwind-Tour-of-Picocli.adoc
- docs/A-Whirlwind-Tour-of-Picocli.html
- docs/index.adoc
- docs/index.html
- docs/man/1.x/index.html
- docs/man/2.x/index.html
- docs/man/3.x/index.html
- docs/man/3.x/quick-guide.html
- docs/quick-guide.adoc
- docs/quick-guide.html
I've been studying documentation for past few days and came across some minor issues that I felt would be a pity to let hem slip. Such a great work deserves perfection for all that matters.
Hope these are seen relevant and get pulled in.
> Revised documentation

- src/main/java/picocli/CommandLine.java
Simplified detection of getter & setter in TypedMember constructor
> Simplified detection of getter & setter in TypedMember constructor

- src/main/java/picocli/CommandLine.java
- src/test/java/picocli/Issue1528.java
Allow aliases of a CommandSpec that is already a subcommand to be properly & consistently modified.
Resolves #1528
Doesn't yet contain tests.  Wanted feedback before I implement tests.
Will add tests and whatever else is requested once the current state of the PR has been reviewed.
> Allow aliases of a CommandSpec that is already a subcommand to be properly & consistently modified.

- src/main/java/picocli/CommandLine.java
Minor cleanup in `CommandLine`
> CommandLine cleanup

- src/main/java/picocli/CommandLine.java
- src/test/java/picocli/GenericTest.java
Improvement for issue #1396. This will also add `CommandLine.UseDefaultConverter` which can be used as marker for default converter fallback.
> Support for generic types in containers

- picocli-groovy/src/test/groovy/picocli/groovy/PicocliBaseScript2Test.groovy
- src/main/java/picocli/CommandLine.java
- src/test/java/picocli/AutoCompleteTest.java
- src/test/java/picocli/Demo.java
- src/test/java/picocli/HelpSubCommandTest.java
- src/test/java/picocli/HelpTest.java
- src/test/java/picocli/InterpolatedModelTest.java
> Bugfix: Help command header text incorrect voice, missing full stop

- docs/index.adoc
While running the sample code, I realized that there is a minor glitch here: if there is no description given for the interactive option, there are opening and closing braces which make no sense without the description string:
```
Enter value for --interactive (): 
```
Would be nice if these braces were supressed if no description string is given.
> User guide, chapter 3.2.3. Forcing Interactive Input: code sample: add Kotlin version

- docs/index.adoc
- src/main/java/picocli/CommandLine.java
A couple of improvements and mainly fixes to the manual.
I didn't find whether you replace versions manually or somehow automated.
In the last paragraph there is a link to `CommandLine.java` that still pointed to `4.6.3-SNAPSHOT` while the remaining document points to `4.7.0-SNAPSHOT`, so however you do the replacement, that spot was missed.
> Doc improvements

- picocli-codegen/src/main/java/picocli/codegen/docgen/manpage/ManPageGenerator.java
As described in https://github.com/remkop/picocli/issues/1696, this fix utilizes the `ArgGroupSpec#allOptionsNested()` and `ArgGroupSpec#allPositionalParametersNested()` to list options under the proper group in the asciidoc output.
Note that this fix may cause an option to be shown multiple times in the output when nesting multiple ArgGroups with headings. For example, if an ArgGroup with heading `Top` contains another ArgGroup with heading `Nested`, then any options defined in the `Nested` group will be listed under both `Top` and `Nested` groups in the asciidoc output. Not sure whether this is a valid/common use case though, and functionally both `ArgGroups` contain that option (directly or indirectly), so it's not even really wrong.
For reference, following is a sample command class …
> [https://github.com/remkop/picocli/issues/1696] Fix asciidoc output for nested ArgGroups

- src/main/java/picocli/CommandLine.java
- src/test/java/picocli/HelpTest.java
This is a fix proposal for https://github.com/remkop/picocli/issues/1708. 
The idea is to avoid exception when the screen is too small and just let setUsageHelpLongOptionsMaxWidth set the newValue when valid.
> [Issue 1708] Ignore invalid values in setUsageHelpLongOptionsMaxWidth

- picocli-annotation-processing-tests/src/test/java/picocli/annotation/processing/tests/Issue1713Test.java
- picocli-annotation-processing-tests/src/test/resources/picocli/issue1713/Command.java
- picocli-codegen/src/main/java/picocli/codegen/annotation/processing/CompileTimeTypeInfo.java
> [Issue 1713] Support optional booleans in annotation processor

- picocli-annotation-processing-tests/src/test/java/picocli/annotation/processing/tests/AbstractCommandSpecProcessorTest.java
- picocli-annotation-processing-tests/src/test/resources/picocli/examples/validation/InvalidFinal.java
- picocli-codegen/src/main/java/picocli/codegen/annotation/processing/AnnotationValidator.java
> [issue 1387] Validate final primitive|String fields w/ Option|Parameters annotations

- src/main/java/picocli/CommandLine.java
- src/test/java/picocli/HelpTest.java
In this pr it was included some log info for invalid scenarios from this issue: https://github.com/remkop/picocli/issues/1708
> [Issue: #1708] Including log info for invalid values scenario

- RELEASE-NOTES.md
- docs/announcing-picocli-1.0.adoc
- docs/build-great-native-cli-apps-in-java-with-graalvm-and-picocli.adoc
- docs/groovy-2.5-clibuilder-renewal-part1.adoc
- docs/groovy-2.5-clibuilder-renewal.adoc
- docs/index.adoc
- docs/picocli-on-graalvm.adoc
- gradle/docs.gradle
- picocli-codegen/README.adoc
- picocli-codegen/src/main/java/picocli/codegen/aot/graalvm/DynamicProxyConfigGenerator.java
- picocli-codegen/src/main/java/picocli/codegen/aot/graalvm/ReflectionConfigGenerator.java
- picocli-codegen/src/main/java/picocli/codegen/aot/graalvm/ResourceConfigGenerator.java
- picocli-shell-jline2/README.md
- src/main/java/overview.html
- src/main/java/picocli/CommandLine.java
This PR
* fixes broken links (docu, javadocs)
* fixes several typos
* updates asciidoctorj to latest version 2.5.5.
> Fixing broken links and typos

- src/main/java/picocli/CommandLine.java
- src/test/java/picocli/Issue1767.java
This PR fixes https://github.com/remkop/picocli/issues/1767, based on the IScoped approach discussed in the issue
> Fix #1767 - NPE on OptionSpec.getValue() (IScoped)

- src/main/java/picocli/CommandLine.java
- src/test/java/picocli/HelpTest.java
Fix and unit test for issue #1834 .
Thanks again @remkop for the fix.  ☺
> Fix and unit test for issue 1834

- src/test/java/picocli/CommandLineTypeConversionTest.java
When I have a `char[]`-typed `@Option` in my command-line object, I get an error when trying to set it from the command line:
Invalid value for option '-charArray' (<charArrayField>): 'abcd' is not a single character
It appears that Picocli treats `char[]` as `char`. The expected behavior instead would be that the input `String` is converted to `char[]` using its `toCharArray()` method.
Couple more notes:
- Using `char[]` as the data type is a pretty common thing when the parameter is a password. The array can be manually zeroed when the password is no longer needed, thus completely removing it from memory while its parent object still lives.
- Using `String` for the same purpose is sub-optimal, as JVM does all kinds of magic with `Strings` and the password could, for example, be interned …
> Introduce a failing test for char[] type conversion

- src/main/java/picocli/AutoComplete.java
- src/test/java/picocli/AutoCompleteTest.java
- src/test/resources/bashify_completion.bash
- src/test/resources/basic.bash
- src/test/resources/hyphenated_completion.bash
- src/test/resources/picocompletion-demo-help_completion.bash
- src/test/resources/picocompletion-demo_completion.bash
> Fix path completion not working with directory names

- src/main/java/picocli/CommandLine.java
- src/test/java/picocli/MixinTest.java
Fix and unit test for issue #1836 .
`initAliases` didn't exist, so please let me know if it looks like I implemented it incorrectly.
> Fix and unit test for issue 1836

- docs/index.adoc
> Use the new official native-maven-plugin

- src/main/java/picocli/CommandLine.java
`booleanValue` returns a `boolean`, so no need to box it into a `Boolean`
> Avoid using boxed boolean in applyValueToSingleValuedField

- picocli-codegen/src/test/java/picocli/codegen/docgen/manpage/ManPageGeneratorTest.java
- picocli-codegen/src/test/resources/manpagegenerator/main_class.adoc
- picocli-codegen/src/test/resources/testEndOfOptionsWithoutOptions.manpage.adoc
- picocli-codegen/src/test/resources/testHiddenOptions.manpage.adoc
Fix 3 failing tests in ManPageGeneratorTest (testEndOfOptionsWithoutOptions, testNamelessCommand, and testHiddenOptions) by updating their respective resource files to account for the additional new lines and white space characters.
> [#1930] fix 3 failing tests in ManPageGeneratorTest

- gradle/docs.gradle
This PR bumps dependency `asciidoctorj` to latest released version.
> Bump asciidoctorj to latest version

- picocli-tests-java567/src/test/java/picocli/HelpAnsiHeuristicsTest.java
- picocli-tests-java9plus/src/test/java/picocli/AutoCompleteSystemExitTest.java
- picocli-tests-java9plus/src/test/java/picocli/HelpAnsiHeuristicsTest.java
- src/main/java/picocli/CommandLine.java
- src/test/java/picocli/HelpAnsiTest.java
- src/test/java/picocli/Issue1125_1538_OptionNameOrSubcommandAsOptionValue.java
- src/test/java/picocli/ModelTransformerTest.java
Fixes #1975 
isJansiConsoleInstalled() was repeatedly called
in a loop from the TextTable#toString method,
which caused performance problems due to the
constant calls to Class#forName.  This change
caches the result from isJansiConsoleInstalled so
it doesn't repeatedly call Class#forName, which
cannot change at runtime.
> Fixed isJansiConsoleInstalled performance issue

- src/main/java/picocli/CommandLine.java
- src/test/java/picocli/UnmatchedArgumentExceptionTest.java
Re: https://github.com/remkop/picocli/issues/2026
> Subcommand suggestions

- src/main/java/picocli/CommandLine.java
- src/test/java/picocli/MapOptionsTest.java
This fixes issue #2035 seen in my own code when using "mapFallbackValue" on an inherited Option.  Also added some unit tests for both inherited Option and Parameters that all failed without this fix.
> Fixes #2035 - include mapFallbackValue for inherited opts

- src/main/java/picocli/CommandLine.java
https://github.com/remkop/picocli/issues/2083
> Update logic for detecting if the output stream is connected to a terminal

- picocli-shell-jline3/README.md
- picocli-shell-jline3/src/test/java/picocli/shell/jline3/example/Example.java
ConfigurationPath cannot be null anymore since commit 9706ead in jline3. An Objects.requireNonNull check now requires a valid ConfigurationPath.
> Fix NPE in jline3 Example as ConfigurationPath cannot be null anymore

- picocli-shell-jline3/src/main/java/picocli/shell/jline3/PicocliCommands.java
I've added a bugfix to hide "hidden" options in the command description shown by JLine3.
> Don't show hidden commands in JLine3 command description

- docs/index.adoc
These two link were broken:
https://s3.amazonaws.com/github/ribbons/forkme_right_red_aa0000.png
https://www.graalvm.org/resources/img/logo-colored.svg
> Doc: Fix broken link
