remkop/picocli

examples/src/main/java/picocli/examples/PopulateFlagsMain.java
examples/src/main/java/picocli/examples/PopulateFlagsWithLongNamesMain.java
examples/src/main/java/picocli/examples/PopulateHelpRequestedMain.java
examples/src/main/java/picocli/examples/PopulateOptionsWithValuesMain.java
examples/src/main/java/picocli/examples/PopulatePositionalParametersMain.java
examples/src/main/java/picocli/examples/TODO

This is supposed to be a preview of how the usage examples I'm going to write will look like, so no merge is requested at this point. Just let me know if the style is okay like this or if you'd like to have them differently.
I'll add more later, of course and update this pull request until I'm done.

Java examples for #223.

---

src/main/java/picocli/CommandLine.java
src/test/java/picocli/CommandLineTest.java

Issue #159
void setUsageWidth(int value)
int getUsageWidth()
To make configurable the help width

Make help width configurable

---

src/main/java/picocli/CommandLine.java
src/test/java/picocli/CommandLineHelpTest.java

This PR  add the ability to specify the usage help width via the `picocli.usage.width` as discussed, therefore it deprecates PR #281.

Add ability to control usage width with system property

---

build.gradle
src/main/java/picocli/AutoComplete.java
src/main/java/picocli/CommandLine.java
src/test/java/picocli/CommandLineHelpTest.java
src/test/java/picocli/CommandLineModelTest.java
src/test/java/picocli/CommandLineParseWithHandlersTest.java
src/test/java/picocli/CommandLineTest.java

This PR fixes all unchecked, deprecation compiler warnings.

 Fix unchecked, deprecation warnings

---

src/main/java/picocli/AutoComplete.java
src/test/java/picocli/AutoCompleteTest.java
src/test/resources/basic.bash
src/test/resources/hyphenated_completion.bash
src/test/resources/picocompletion-demo_completion.bash

Fix option argument handling in autocompletion scripts

---

src/main/java/picocli/CommandLine.java
src/test/java/picocli/CommandLineHelpTest.java

Format the description or header of subcommands

[#301] Unformatted description configuration in generated help

---

picocli-core-module/build.gradle
picocli-core-module/src/main/java/module-info.java
settings.gradle

Adding JPMS module définition to picocli.
Adding new subproject picocli-core-module

Jmps java 9

---

src/main/java/picocli/CommandLine.java

-Align with other headers and descriptions
-Adjust some comments

Imperative mood for HelpCommand header

---

docs/index.adoc

Documentation: fixing broken link

---

docs/index.adoc

User manual: minor fixes

---

src/main/java/picocli/AutoComplete.java
src/test/java/picocli/AutoCompleteTest.java
src/test/resources/picocompletion-demo_completion.bash

Add Bash completion of positional parameters based on the position in the COMP_WORDS completion array.
Fixed issue: #468

Positional params completion

---

picocli-examples/annotation-processing/example-gradle-project-kotlin-graal-nativeimage/.gitignore
picocli-examples/annotation-processing/example-gradle-project-kotlin-graal-nativeimage/README.md
picocli-examples/annotation-processing/example-gradle-project-kotlin-graal-nativeimage/build.gradle
picocli-examples/annotation-processing/example-gradle-project-kotlin-graal-nativeimage/src/main/kotlin/picocli/examples/kotlin/Checksum.kt

Gradle project setup. Example code copied from picocli-examples/src/main/kotlin/picocli/examples/kotlin/Checksum.kt

Added example Gradle project with Kotlin and Graal Native Image

---

src/main/java/picocli/CommandLine.java
src/test/java/picocli/AtFileTest.java

Fix #984 
Add judgment on atFileParameterList.

Fix not shown parameter heading under specific condition

---

docs/index.adoc
picocli-examples/src/main/java/picocli/examples/casesensitivity/CaseInsensitiveDemo.java
picocli-examples/src/main/java/picocli/examples/casesensitivity/POSIXOptionResembleDemo.java
picocli-examples/src/main/java/picocli/examples/casesensitivity/ScopedCaseSensitivityDemo.java

Finished docs on case sensitivity (#9), and add some examples.

---

docs/index.adoc
docs/index.html

Hi Remkop,
For issue #1028 , I've added descriptions about java 15's text block in user manual in both html and adoc files.
This may save your time of writing document.
Enderaoe

add description about text blocks (#1028)

---

src/main/java/picocli/CommandLine.java
src/test/java/picocli/NegatableOptionTest.java

Fixes #1022 , a new test is added.

Check for duplicate negated when adding non-negatable option (#1022)

---

src/main/java/picocli/CommandLine.java
src/test/java/picocli/CommandLineTest.java
src/test/java/picocli/HelpTest.java
src/test/java/picocli/LenientParsingTest.java
src/test/java/picocli/TypeConversionTest.java

Hi! Does that meet your expectation?  I will be glad if that helps.

Remkop#995 v2

---

RELEASE-NOTES.md
picocli-codegen/README.adoc
picocli-codegen/src/main/java/picocli/codegen/docgen/manpage/ManPageGenerator.java

Man page generator: fix incorrect asciidoctor call in synopsis

---

picocli-codegen/src/main/java/picocli/codegen/docgen/manpage/ManPageGenerator.java

Man page generator: add documentation about creating language variants

---

docs/index.adoc
docs/quick-guide.adoc
picocli-examples/src/main/java/picocli/examples/typeconverter/InetSocketAddressConverterDemo.java

Improve InetSocketAddressConverter demo

---

docs/index.adoc

BTW: what does this mean (index.adoc, line 6008): 
`this command adds the frup to the frooble`

Manual: add tabs with Kotlin code for samples (chapters 8, 16, 20)

---

docs/index.adoc

This PR add tabs with Kotlin code for the samples in chapter 21: Tips & Tricks.
It also fixes the Java code sample in chapter 21.9. Hexadecimal Values (Java 8 lambdas).

Manual: add tabs with Kotlin code for samples (Chapter 21: Tips & Tricks)

---

docs/index-docinfo-footer.html
docs/index-docinfo.html
docs/index.adoc
docs/quick-guide-docinfo-footer.html
docs/quick-guide-docinfo.html
docs/quick-guide.adoc

Implemented code folding following the discussion/instructions found [here](https://github.com/asciidoctor/asciidoctor/issues/699).

Implement foldable TOC for user manual and quick guide

---

docs/index.adoc

* Adds sections about using Mockito to documentation
* Closes #1243

Add Mocking section to index.adoc

---

src/test/java/picocli/SubcommandTests.java

The shows two calls that should normally be equivalent, but that have different end results, due to the incorrect handling of the "initialized" parameter state.
I tried to make them share the "initialized" object, as an initial attempt to make the test pass, but unfortunately, the PositionParameterSpec object is different than the one contained by the root CommandSpec, so the initialized check fails anyway.
In any case, this test failure is useful for showing the problem.

Add showcase example for issue #1250

---

README.md

include jbang syntax for dep usage

---

docs/index-docinfo-footer.html
docs/index.adoc
docs/quick-guide.adoc
gradle.properties

This PR includes the following enhancements:
- manual: present build scripts (Gradle, Maven, ...) in tabs
- manual, quick guide: minor corrections
- bump to latest versions (SpringBoot, ...)

Manual: present build scripts in tabs

---

src/main/java/picocli/CommandLine.java

PR following up on your proposal in #1296.

Extend javadoc of IParameterConsumer interface

---

README.md

Fix the broken logo links in README.md

Fix README adoption logos

---

build.gradle
docs/build-great-native-cli-apps-in-java-with-graalvm-and-picocli.adoc
docs/index.adoc
gradle/docs.gradle
gradle/wrapper/gradle-wrapper.properties
picocli-codegen/README.adoc
picocli-codegen/build.gradle
picocli-codegen/src/main/java/picocli/codegen/aot/graalvm/DynamicProxyConfigGenerator.java
picocli-codegen/src/main/java/picocli/codegen/aot/graalvm/JniConfigGenerator.java
picocli-codegen/src/main/java/picocli/codegen/aot/graalvm/ReflectionConfigGenerator.java
picocli-codegen/src/main/java/picocli/codegen/aot/graalvm/ResourceConfigGenerator.java
picocli-examples/build.gradle
picocli-examples/src/main/kotlin/picocli/examples/kotlin/subcommands/SubCmdsViaMethods.kt

* Extending documentation (#1457)
* Fix broken and outdated links (GraalVM related)
* Update dependencies related to doc generation

Extend documentation on argument files, fix broken/outdated links

---

docs/apidocs/index-all.html
docs/apidocs/picocli/CommandLine.Model.CommandSpec.html
docs/apidocs/picocli/CommandLine.html
src/main/java/picocli/CommandLine.java

Removed repeated "whether" typo in JavaDoc

Removed repeated "whether" typo in JavaDoc

---

picocli-annotation-processing-tests/src/test/java/picocli/annotation/processing/tests/YamlAssert.java

Fixed org.junit.Assert.assertThat deprecation warning

Fixed org.junit.Assert.assertThat deprecation warning

---

src/main/java/picocli/CommandLine.java

PositionalParamSpec changed to max
https://github.com/remkop/picocli/issues/1384

PositionalParamSpec changed to max

---

gradle/wrapper/gradle-wrapper.properties

Bump gradle from 7.3 to 7.3.1

---

gradle/wrapper/gradle-wrapper.properties

Bump gradle from 7.3.1 to 7.3.3
Fixes log4j vulnerability

Bump gradle from 7.3.1 to 7.3.3

---

src/main/java/picocli/AutoComplete.java
src/test/java/picocli/AutoCompleteTest.java
src/test/resources/bashify_completion.bash
src/test/resources/basic.bash
src/test/resources/hyphenated_completion.bash
src/test/resources/picocompletion-demo-help_completion.bash
src/test/resources/picocompletion-demo_completion.bash

Created a couple of test programs and tested the autocomplete scripts in zsh and bash.

[#1526] Fix use of compinit clobbering existing completions

---

.github/workflows/codeql-analysis.yml
RELEASE-NOTES.md

Fix code scanning alert - SAST #1556

[#1556] add SAST codeql-analysis.yml

---

docs/index.adoc
docs/quick-guide.adoc
gradle/docs.gradle

Documentation: minor corrections (related to #1578).

Bump asciidoctor to latest version

---

picocli-codegen/README.adoc

Picocli-codegen, README.adoc: fix broken link

---

docs/build-great-native-cli-apps-in-java-with-graalvm-and-picocli.adoc
docs/index.adoc
docs/picocli-on-graalvm.adoc
docs/picocli-programmatic-api.adoc
docs/zh/picocli-2.0-groovy-scripts-on-steroids.adoc
gradle/wrapper/gradle-wrapper.properties
picocli-codegen/README.adoc
picocli-codegen/src/main/java/picocli/codegen/aot/graalvm/DynamicProxyConfigGenerator.java
picocli-codegen/src/main/java/picocli/codegen/aot/graalvm/ReflectionConfigGenerator.java
picocli-codegen/src/main/java/picocli/codegen/aot/graalvm/ResourceConfigGenerator.java

This PR
* fixes the anchor links in various links to api docs
* changes links to GraalVM docu to their latest version
* bumps gradle to latest version 7.6

Documentation improvements

---

README.md

This PR closes #1910 by correcting a broken link in README.md.

Fixes broken link in README.md (#1910)

---

docs/index.adoc

This PR fixes a broken link I spotted in the manual.

Manual: fix broken link

---

docs/index.adoc

This refers to https://github.com/remkop/picocli/discussions/1903.
cc @remkop

docs: add GraalVM Native Image demo and Spring Boot Maven Plugin section 

---

picocli-shell-jline3/README.md
picocli-shell-jline3/src/test/java/picocli/shell/jline3/example/Example.java

It's broken (all red) on https://github.com/remkop/picocli/actions.
https://github.com/remkop/picocli/pull/2148 broke it.

Fix broken build

---

docs/index.adoc
docs/index.html

Addresses the issue raised here: https://github.com/remkop/picocli/issues/1650#issuecomment-2123220393
Also fixed mixed line endings (75 CRLF vs 19090 LF) on docs/index.html file to get all lines to end with LF.
@remkop Please let me know if any changes needed in RELEASE-NOTES.md

DOC: User guide, CDI 2.0 (JSR 365) section: fix example and add warning about dynamic proxies

---

README.md

Add missing dependency to example

Add missing dependency to example
